### ISSUE TITLE
NPE when trying to get a list of items from item_storage

### ISSUE THREAD

**Issue by qwert0p** [SirEdvin/UnlimitedPeripheralWorks#15]
Fabric 1.19.2
Unlimited Peripheral Works 0.2.5
Peripheralium 0.4.21-1.19.2
CC: Restitched 1.101.2
<details>
<summary> Log: </summary>
[Server thread/ERROR]: Error running task
java.lang.NullPointerException: Well, that's really something, how did you even get here?
  at dan200.computercraft.shared.util.NBTUtil.assertNonNull(NBTUtil.java:560) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.shared.util.NBTUtil.handler$zmn000$peripheralworks$getNBTHash(NBTUtil.java:543) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.shared.util.NBTUtil.getNBTHash(NBTUtil.java) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.shared.peripheral.generic.data.ItemData.fillBasic(ItemData.java:42) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.shared.peripheral.generic.data.ItemData.fill(ItemData.java:52) ~[cc-restitched-1.101.2.jar:?]
  at site.siredvin.peripheralium.extra.plugins.ItemStoragePlugin.items(ItemStoragePlugin.kt:38) ~[peripheralium-0.4.21-1.19.2.jar:?]
  at site.siredvin.peripheralium.extra.plugins.ItemStoragePlugin$cc$items3.apply(CC generated method) ~[?:?]
  at dan200.computercraft.core.asm.PeripheralMethod.lambda$static$0(PeripheralMethod.java:21) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.core.lua.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:34) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.core.computer.MainThreadExecutor.execute(MainThreadExecutor.java:143) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.core.computer.MainThread.executePendingTasks(MainThread.java:157) ~[cc-restitched-1.101.2.jar:?]
  at dan200.computercraft.shared.proxy.ComputerCraftProxyCommon.lambda$registerHandlers$3(ComputerCraftProxyCommon.java:105) ~[cc-restitched-1.101.2.jar:?]
  at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:40) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-db0fd3f5dc0d6099.jar:?]
  at net.minecraft.server.MinecraftServer.handler$zeg000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:2816) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
  at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
  at java.lang.Thread.run(Thread.java:833) [?:?]
</details>

**Comment by SirEdvin** [comment]
How is this even possible :) Oh, that a shame. 

For quick fix you can rollback to 0.2.4, it should remove the mixin logic. I will try to release a fix today/tommorow.

**Comment by SirEdvin** [comment]
Okey, you can use 0.2.6 version, this issue should be fixed

**Comment by qwert0p** [comment]
Yep, everything is fixed now, thanks!
